### ISSUE TITLE
Crash when updating "Currency"

### ISSUE THREAD

**Issue by iexos** [EvanRespaut/Equate#14]
Fresh install, on LineageOS 14.1

Looks like when pulling the current exchange rates it crashes (shortly after selecting "Currency")

logcat:
```
02-21 00:39:51.845 22309 22328 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
02-21 00:39:51.845 22309 22328 E AndroidRuntime: Process: com.llamacorp.equate, PID: 22309
02-21 00:39:51.845 22309 22328 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
02-21 00:39:51.845 22309 22328 E AndroidRuntime:        at android.os.AsyncTask$3.done(AsyncTask.java:325)
02-21 00:39:51.845 22309 22328 E AndroidRuntime:        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
02-21 00:39:51.845 22309 22328 E AndroidRuntime:        at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
02-21 00:39:51.845 22309 22328 E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
02-21 00:39:51.845 22309 22328 E AndroidRuntime:        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
02-21 00:39:51.845 22309 22328 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
02-21 00:39:51.845 22309 22328 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
02-21 00:39:51.845 22309 22328 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:761)
02-21 00:39:51.845 22309 22328 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.trim()' on a null object reference
02-21 00:39:51.845 22309 22328 E AndroidRuntime:        at java.lang.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1068)
02-21 00:39:51.845 22309 22328 E AndroidRuntime:        at java.lang.Double.parseDouble(Double.java:547)
02-21 00:39:51.845 22309 22328 E AndroidRuntime:        at com.llamacorp.equate.unit.YahooXmlParser.readResource(YahooXmlParser.java:142)
02-21 00:39:51.845 22309 22328 E AndroidRuntime:        at com.llamacorp.equate.unit.YahooXmlParser.readList(YahooXmlParser.java:82)
02-21 00:39:51.845 22309 22328 E AndroidRuntime:        at com.llamacorp.equate.unit.YahooXmlParser.findResources(YahooXmlParser.java:62)
02-21 00:39:51.845 22309 22328 E AndroidRuntime:        at com.llamacorp.equate.unit.YahooXmlParser.parse(YahooXmlParser.java:45)
02-21 00:39:51.845 22309 22328 E AndroidRuntime:        at com.llamacorp.equate.unit.UnitTypeUpdater.getCurrRates(UnitTypeUpdater.java:155)
02-21 00:39:51.845 22309 22328 E AndroidRuntime:        at com.llamacorp.equate.unit.UnitTypeUpdater.updateRatesWithXML(UnitTypeUpdater.java:112)
02-21 00:39:51.845 22309 22328 E AndroidRuntime:        at com.llamacorp.equate.unit.UnitTypeUpdater.access$000(UnitTypeUpdater.java:24)
02-21 00:39:51.845 22309 22328 E AndroidRuntime:        at com.llamacorp.equate.unit.UnitTypeUpdater$UpdateYahooXMLAsyncTask.doInBackground(UnitTypeUpdater.java:75)
02-21 00:39:51.845 22309 22328 E AndroidRuntime:        at com.llamacorp.equate.unit.UnitTypeUpdater$UpdateYahooXMLAsyncTask.doInBackground(UnitTypeUpdater.java:63)
02-21 00:39:51.845 22309 22328 E AndroidRuntime:        at android.os.AsyncTask$2.call(AsyncTask.java:305)
02-21 00:39:51.845 22309 22328 E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
02-21 00:39:51.845 22309 22328 E AndroidRuntime:        ... 4 more
02-21 00:39:51.850  1605  3648 W ActivityManager:   Force finishing activity com.llamacorp.equate/.view.CalcActivity
02-21 00:39:51.863  1605  3648 W ActivityManager:   Force finishing activity com.llamacorp.equate/.view.CalcActivity
02-21 00:39:51.863  1605  3648 W ActivityManager: Duplicate finish request for ActivityRecord{48276b1 u0 com.llamacorp.equate/.view.CalcActivity t137 f}
```

**Comment by EvanRespaut** [comment]
Hmm interesting. There seems to be an issue with parsing the XML file downloaded from Yahoo, but strange that I've never seen that before. If you haven't already, can you try to clear the application cache and data (under settings, applications, Equate). I'm guessing that happens every time?

**Comment by iexos** [comment]
It happens *almost* every time. I tried maybe 20 times, once (after reinstall and reboot) it actually worked. Also took a couple of seconds when it worked, when it crashes it is almost instantly.

Tried to reproduce making it work with rebooting and reinstalling, crashes every time.

LineageOS14.1 is not marked as stable, I am using the latest nightly. I cannot fully rule out that it has to do with that.

**Comment by iexos** [comment]
Actually, it now happens on my old phone as well (didn't try for a while). Did Yahoo change something?

**Comment by dalb8** [comment]
I have this as well. started happening yesterday. stock LG g4 on Android 6

**Comment by lupa18** [comment]
Here the same

**Comment by EvanRespaut** [comment]
Fixed it.  Update should be live on google play in a few hours. Let me know if anyone still has issues.

**Comment by dalb8** [comment]
its working again and I'm still using the old version

**Comment by EvanRespaut** [comment]
Yahoo seems to be sometimes adding empty elements into the XML. The new code will ignore them and the old code breaks when it sees them. So sometimes the old will still work, but I have new should always work :)

**Comment by trmendes** [comment]
Is there an update for the f-droid store? Mine still crashing here

**Comment by EvanRespaut** [comment]
Sorry, forgot to push the tag to Github for f-droid to update.  Just did that so it should be updated on f-droid soon.

**Comment by trmendes** [comment]
@EvanRespaut No uodates on f-droid yet

**Comment by EvanRespaut** [comment]
Sorry about that, the branch with the name v1.4 was blocking the new update for f-droid.  It's up now.

**Comment by iexos** [comment]
Tested and works. Thank you! :)
